In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 一个样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [2]:
import pandas as pd

data = pd.read_csv(data_file)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [4]:
nan_numer = data.isnull().sum(axis=1)
nan_numer

0    1
1    1
2    1
3    2
dtype: int64

In [5]:
nan_max_id = nan_numer.idxmax()
nan_max_id

3

In [8]:
data_delete = data.drop([nan_max_id], axis=0)
data_delete

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100

In [9]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] # index location
inputs = inputs.fillna(inputs.mean(numeric_only=True)) # fill nan with mean value of numeric columns
inputs

C:\Users\zhang\AppData\Local\Temp/ipykernel_11804/3114718444.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [10]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

inputs,outputs,data

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [11]:
import torch

# 先转换为 float32，避免混合列产生 object 类型数组
X = torch.tensor(inputs.to_numpy(dtype='float32'))
y = torch.tensor(outputs.to_numpy(dtype='float32'))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))